fix: _checkPermission is called twice when force is set to true
capacitor-community/barcode-scanner pull request #82
Opened 2021-09-24 10:54 UTC by ec-lmayr

Finally found the source for issue #71 .

_checkPermission was called twice when force is set to true, and the second call resolves the plugin call before the user has responded to the permission request.

Can be installed from here:
https://github.com/ec-lmayr/barcode-scanner/tree/fix/build-on-install

This includes the _checkPermission fix as well as a change that the plugin is built when installed from github directly.

closes #71

2021-09-26 07:53 UTC, tafelnl requested changes
Could you please sign the commit? This is required by the Capacitor team.

2021-09-26 07:53 UTC, tafelnl commented on android/src/main/java/com/dutchconcepts/capacitor/barcodescanner/BarcodeScanner.java
> +        }else{
Could you rewrite this as `} else {` ?

2021-09-26 07:53 UTC, tafelnl commented
Thanks for the PR! If just reviewed it. Could you address those issues? I will then go ahead and merge ASAP.

2021-09-27 08:32 UTC, tafelnl commented
Thanks! Unfortunately, yes, all commits must be signed:
![image](https://user-images.githubusercontent.com/35837839/134872951-96aff262-e046-43d3-9387-a25245e3a4ed.png)

2021-09-27 09:17 UTC, ec-lmayr commented
Ok, the signing has become a bit of a mess. Must all commits be signed? If so, I will delete the pull requests and create new ones.

2021-09-27 09:17 UTC, closed without merging